### ISSUE TITLE
[COMPILER] `ensure` code can run twice

### ISSUE THREAD

**Issue by tenderlove** [ruby/prism#2212] opened 2024-01-18 23:26 UTC
From `test_flow.rb`:

```ruby
def m()
  a = []
ensure
  a << 5
  return a
end
m
```

`a` should be `[5]`, but we get `[5, 5]`

**Comment by peterzhu2118** [comment] 2024-01-19 15:59
I think this is a duplicate of #2176 and fixed in ruby/ruby#9580.

**Comment by tenderlove** [comment] 2024-01-19 17:41
It seems to be failing on ruby/ruby@efe4b8ac0f5de49dcb20806f5a6c2d90273e8d52. I haven't investigated why it's doing this though

**Comment by eileencodes** [comment] 2024-01-19 18:13
The instructions are doubled up. 8-18 and 21-31 are the same, and should only appear once.

```
0000 newarray                               0                         (  62)[Li]
0002 dup
0003 setlocal                               a@0, 0
0006 nop
0007 nop                                                              (  62)
0008 getlocal                               a@0, 0                    (  64)[Li]
0011 putobject                              5
0013 send                                   <calldata!mid:<<, argc:1, ARGS_SIMPLE>, nil
0016 pop
0017 pop                                                              (  65)
0018 getlocal                               a@0, 0[Li]
0021 getlocal                               a@0, 0                    (  64)[Li]
0024 putobject                              5
0026 send                                   <calldata!mid:<<, argc:1, ARGS_SIMPLE>, nil
0029 pop
0030 pop                                                              (  65)
0031 getlocal                               a@0, 0[Li]
0034 leave                                  [Re]
0035 leave                                  [Re]
0036 putnil
0037 pop                                                              (  62)
0038 leave                                                            (  61)
```

**Comment by peterzhu2118** [comment] 2024-01-19 18:48
I think ruby/ruby@efe4b8ac0f5de49dcb20806f5a6c2d90273e8d52 broke this. I checked out ruby/ruby@200d3cc14d4c98bfee3826bda9c0e09a1113d939 and it worked fine.

**Comment by peterzhu2118** [comment] 2024-01-19 18:48
Oh never mind 🤦 , you already commented this https://github.com/ruby/prism/issues/2212#issuecomment-1900828873

**Comment by eileencodes** [comment] 2024-01-19 19:57
Fixed by https://github.com/ruby/ruby/pull/9619

**Closed** 2024-01-19 21:04 UTC
Labels: compiler
