### ISSUE TITLE
`Prism::Translation::Parser` assigns wrong location to strings after multibyte characters

### ISSUE THREAD

**Issue by dvandersluis** [ruby/prism#3194] opened 2024-10-29 17:33 UTC
When there are (certain?) multibyte characters preceding a multiline string, the values in the `offset_cache` are wrong which results in the wrong location for `Parser::Source::Range`. The character in the below example is `U+FF11 FULLWIDTH DIGIT ONE`.

Relates to https://github.com/rubocop/rubocop/issues/13204

Minimal reproduction test case:

```patch
Index: test/prism/fixtures/whitequark/multibyte_offset.txt
<+>UTF-8
===================================================================
diff --git a/test/prism/fixtures/whitequark/multibyte_offset.txt b/test/prism/fixtures/whitequark/multibyte_offset.txt
new file mode 100644
--- /dev/null	(date 1730222542625)
+++ b/test/prism/fixtures/whitequark/multibyte_offset.txt	(date 1730222542625)
@@ -0,0 +1,3 @@
+# １
+"abc
+"
```

Test output:

```
=========================================================================================================
Failure: test_whitequark/multibyte_offset.txt(Prism::ParserTest)
/src/prism/test/prism/ruby/parser_test.rb:276:in `assert_equal_tokens'
/src/prism/test/prism/ruby/parser_test.rb:212:in `assert_equal_parses'
/src/prism/test/prism/ruby/parser_test.rb:175:in `block (2 levels) in <class:ParserTest>'
expected: [:tSTRING_CONTENT, ["abc\n", #<Parser::Source::Range whitequark/multibyte_offset.txt 9...13>]]
actual: [:tSTRING_CONTENT, ["abc\n", #<Parser::Source::Range whitequark/multibyte_offset.txt 7...11>]]
<[:tSTRING_CONTENT,
 ["abc\n", #<Parser::Source::Range whitequark/multibyte_offset.txt 9...13>]]> expected but was
<[:tSTRING_CONTENT,
 ["abc\n", #<Parser::Source::Range whitequark/multibyte_offset.txt 7...11>]]>

diff:
  [:tSTRING_CONTENT,
?  ["abc\n", #<Parser::Source::Range whitequark/multibyte_offset.txt 9...13>]]
?                                                                    7    1
?                                                                    ?    ?
=========================================================================================================

```

**Comment by kddnewton** [comment] 2024-11-04 16:40
Yeah, this is definitely an ongoing known problem. This is effectively a duplicate of https://github.com/ruby/prism/issues/2539, so I'm going to close this one just because we've been tracking the issue there. Thanks for the report!

**Closed by kddnewton** 2024-11-04 16:40 UTC

**Comment by dvandersluis** [comment] 2024-11-04 16:44
Thanks @kddnewton! Do you want me to add any of this as a comment there?

**Comment by kddnewton** [comment] 2024-11-04 16:53
Sure!
