### ISSUE TITLE
[COMPILER] Incorrect instructions with kwsplat causes failed assertion

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#2119] opened 2024-01-02 19:05 UTC
Minimal repro:

`[**{}]`

Causes `Assertion Failed: ../vm_core.h:1375:VM_ENV_FLAGS:FIXNUM_P(flags)`

**Comment by peterzhu2118** [comment] 2024-01-15 16:34
Duplicate of #2155 and should be fixed by ruby/ruby#9540.

**Closed by peterzhu2118** 2024-01-15 16:34 UTC
Labels: compiler
